name: Build and Deploy Dinamis
on:
  push:
    branches: [ main ]
    [cite_start]paths: ['web-dinamis/**'] # <--- Ini fitur Paths Filter agar efisien 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Push Image
        run: |
          docker build -t namadocker/web-dinamis:latest ./web-dinamis
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker push namadocker/web-dinamis:latest
      
      - name: Deploy ke AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull namadocker/web-dinamis:latest
            docker compose up -d --force-recreate