name: Deploy Dinamis

on:
  push:
    branches: [ main ]
    [cite_start]paths: ['web-dinamis/**'] # Menggunakan Paths Filter agar efisien 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dan Deploy
        run: echo "Pipeline berhasil diaktifkan!"